-- users table already provided by Supabase Auth (auth.users). We'll create application tables:

-- transactions (deposits/withdraws)
create table public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  type text not null check (type in ('deposit','withdraw')),
  amount numeric(12,2) not null,
  description text,
  created_at timestamptz default now()
);

-- portfolio (user holdings)
create table public.portfolio (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  symbol text not null,
  shares numeric,
  avg_price numeric,
  created_at timestamptz default now()
);

-- watchlist (user saved symbols)
create table public.watchlist (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  symbol text not null,
  created_at timestamptz default now()
);

-- Row level security: allow authenticated users to manage own rows
alter table public.transactions enable row level security;
create policy "transactions_insert" on public.transactions for insert using (auth.role() = 'authenticated');
create policy "transactions_select" on public.transactions for select using (auth.uid() = user_id);
create policy "transactions_delete" on public.transactions for delete using (auth.uid() = user_id);
create policy "transactions_update" on public.transactions for update using (auth.uid() = user_id);

alter table public.portfolio enable row level security;
create policy "portfolio_manage" on public.portfolio for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

alter table public.watchlist enable row level security;
create policy "watchlist_manage" on public.watchlist for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
